# Site settings
title: HongShield
SEOTitle: HongShield的博客 | HongShield's Blog
header-img: img/post-bg-desk.jpeg
email: admin@hongshield.cn
description: "漫漫人生路，上下求索！"
keyword: "HS, HS Blog, HongShield的博客, HongShield, Web, network"
url: "http://hongshield.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/hongshield/hongshield.github.io.git" # you code repository

# Sidebar settings
sidebar: true                                  # whether or not using Sidebar.
sidebar-about-description: "探索，让未来多一种可能。"
sidebar-avatar: /img/apple-touch-icon.png      # use absolute URL, seeing it's used in both `/` and `/about/`
 

# SNS settings
RSS: true
# weibo_username:     
# zhihu_username:    hongshield
github_username:    hongshield
# csdn_username:    Mx_zH
linkedin_username: hong-shield-275484210
#facebook_username:
#twitter_username: 


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


plugins:
  - jekyll-seo-tag
  - jekyll-admin
  - jekyll-feed
  - jekyll-archives

plugins: [jekyll-paginate]

paginate: 5


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# 评论系统
# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 68fc4840684bf5468c95                           #生成的clientID
  clientSecret: be0046fd5d8fba57b5df25b4ac280aa6f07f1438    #生成的clientSecret
  repo: hongshield.github.io    #仓库名称
  owner: hongshield    #github用户名
  admin: hongshield
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计
# Analytics settings
# Baidu Analytics
ba_track_id: 5ed84f538e893e0fddd9cebc28f67e37

# Google Analytics
# ga_track_id:  ''            # Format: G-xxxxxxxxxx
# 代码在footer.html 底部 


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# Friends
# friends: [
#     {
#         title: "CSDN · HongShield",
#         href: "https://blog.csdn.net/Mx_zH/"
#     }
# ]

